import type { ProductItem, UserProfile } from '../types/index.ts';

export const DEFAULT_PRODUCTS: ProductItem[] = [
  {
    id: '7day_premium',
    title: '7-Day Premium',
    description: 'Perfect for a week of unlimited matches and enhanced discovery.',
    price: 9.99,
    interval: '7days',
    badge: 'Starter',
    category: 'subscription',
    features: [
      'Unlimited Likes',
      'See Who Liked You',
      '5 Free Super Likes',
      '1 Free Profile Boost',
      'Unlimited Rewinds'
    ],
    isActive: true,
  },
  {
    id: 'monthly_premium',
    title: 'Monthly Premium',
    description: 'Our most popular plan for intentional daters looking for real connections.',
    price: 24.99,
    interval: '1month',
    badge: 'Most Popular',
    category: 'subscription',
    features: [
      'All 7-Day features included',
      'Advanced Filters (Lifestyle, Goals)',
      'Incognito Browsing Mode',
      'Priority Likes Delivery',
      '15 Free Super Likes per month',
      '2 Free Boosts per month'
    ],
    isActive: true,
  },
  {
    id: '3month_premium',
    title: '3-Month Premium',
    description: 'Best value for singles committed to finding their special person.',
    price: 49.99,
    interval: '3months',
    badge: 'Best Value',
    category: 'subscription',
    features: [
      'Save over 33% compared to monthly',
      'All Monthly Premium benefits',
      'Continuous Priority Discovery',
      '30 Super Likes bundle',
      '5 Boost passes included',
      'VIP Verified Profile Badge'
    ],
    isActive: true,
  },
  {
    id: 'vip_monthly',
    title: 'VIP Monthly',
    description: 'The ultimate dating experience with personalized AI matchmaking insights.',
    price: 59.99,
    interval: '1month',
    badge: 'Exclusive',
    category: 'subscription',
    features: [
      'Unrestricted VIP Discovery',
      'See Who Liked You instantly',
      'Direct First Message before matching',
      'AI Wingman & Deep Compatibility Reports',
      'Daily Profile Boost during peak hours',
      'Dedicated Priority Safety Concierge'
    ],
    isActive: true,
  },
  // One-time consumables
  {
    id: 'superlikes_pack_5',
    title: '5 Super Likes',
    description: 'Stand out from the crowd and let them know you are genuinely interested.',
    price: 4.99,
    interval: 'one_time',
    category: 'consumable',
    consumableType: 'superlike',
    quantity: 5,
    features: ['3x higher response rate', 'Notifies the person immediately'],
    isActive: true,
  },
  {
    id: 'profile_boost',
    title: 'Profile Boost (30 Mins)',
    description: 'Skip the line and be one of the top profiles in your area for 30 minutes.',
    price: 3.99,
    interval: 'one_time',
    category: 'consumable',
    consumableType: 'boost',
    quantity: 1,
    features: ['Up to 10x more profile views', 'Peak evening visibility'],
    isActive: true,
  },
  {
    id: 'spotlight_pass',
    title: 'Spotlight (1 Hour)',
    description: 'Featured prominently at the top of recommended discovery feeds.',
    price: 7.99,
    interval: 'one_time',
    category: 'consumable',
    consumableType: 'spotlight',
    quantity: 1,
    features: ['Highlighted golden border', 'Top tier placement across your city'],
    isActive: true,
  },
  {
    id: 'rewind_pack_10',
    title: '10 Rewinds',
    description: 'Accidentally passed on someone great? Undo your last swipe instantly.',
    price: 2.99,
    interval: 'one_time',
    category: 'consumable',
    consumableType: 'rewind',
    quantity: 10,
    features: ['Revisit passed profiles', 'Second chance connections'],
    isActive: true,
  }
];

export const ELIGIBLE_DISCOVERY_COUNTRIES: { name: string; flag: string; code: string }[] = [
  { name: 'United States', flag: '🇺🇸', code: 'US' },
  { name: 'United Kingdom', flag: '🇬🇧', code: 'GB' },
  { name: 'Canada', flag: '🇨🇦', code: 'CA' },
  { name: 'Australia', flag: '🇦🇺', code: 'AU' },
  { name: 'United Arab Emirates', flag: '🇦🇪', code: 'AE' },
  { name: 'Germany', flag: '🇩🇪', code: 'DE' },
  { name: 'France', flag: '🇫🇷', code: 'FR' },
  { name: 'Spain', flag: '🇪🇸', code: 'ES' },
  { name: 'Italy', flag: '🇮🇹', code: 'IT' },
  { name: 'Netherlands', flag: '🇳🇱', code: 'NL' },
];

export const INITIAL_DISCOVERY_PROFILES: UserProfile[] = [
  {
    userId: 'user_sophia_ny',
    name: 'Sophia',
    age: 27,
    gender: 'woman',
    interestedIn: 'men',
    city: 'New York',
    country: 'United States',
    showCity: true,
    bio: 'Architect with a passion for sustainable urban design, sourdough baking, and rooftop jazz. Looking for someone intellectually curious who laughs easily and values honesty.',
    photos: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80'
    ],
    interests: ['Architecture', 'Modern Art', 'Specialty Coffee', 'Live Jazz', 'Sustainability'],
    hobbies: ['Pilates', 'Ceramics', 'Reading Biographies', 'Cycling'],
    profession: 'Senior Urban Architect',
    education: 'Columbia University',
    languages: ['English', 'French'],
    relationshipGoal: 'long-term',
    completionPercentage: 100,
    verified: true,
    verificationStatus: 'verified',
    profileVerified: true,
    optedIntoDiscovery: true,
    onlineStatusVisibility: true,
    isIncognito: false,
    lastActiveAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(), // 4 mins ago (Online Now)
    registeredAt: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
    prompts: [
      { id: 'p1', question: 'The hallmark of a great Sunday', answer: 'Browsing independent bookstores in Brooklyn followed by handmade fresh pasta.' },
      { id: 'p2', question: 'My simple pleasures', answer: 'The sound of vinyl records spinning, first sip of Ethiopian pour-over, and crisp autumn mornings.' },
    ],
    lifestyle: {
      drinking: 'socially',
      smoking: 'no',
      workout: 'often',
      pets: 'Golden Retriever lover',
      height: '5 ft 8 in (173 cm)',
    },
    voiceNote: {
      topic: 'My favorite city memory',
      duration: '0:34',
    },
    updatedAt: new Date().toISOString()
  },
  {
    userId: 'user_liam_london',
    name: 'Liam',
    age: 30,
    gender: 'man',
    interestedIn: 'women',
    city: 'London',
    country: 'United Kingdom',
    showCity: true,
    bio: 'Fintech product lead by day, amateur acoustic guitarist by night. Big fan of weekend hikes in Surrey, independent cinema, and trying street food around Soho.',
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80'
    ],
    interests: ['Fintech', 'Acoustic Guitar', 'Indie Cinema', 'Hiking', 'Photography'],
    hobbies: ['Bouldering', 'Vinyl Collecting', 'Cooking Italian', 'Travel'],
    profession: 'Product Director',
    education: 'London School of Economics',
    languages: ['English', 'Spanish'],
    relationshipGoal: 'marriage',
    completionPercentage: 95,
    verified: true,
    verificationStatus: 'verified',
    profileVerified: true,
    optedIntoDiscovery: true,
    onlineStatusVisibility: true,
    isIncognito: false,
    lastActiveAt: new Date(Date.now() - 9 * 60 * 1000).toISOString(), // 9 mins ago (Online Now)
    registeredAt: new Date(Date.now() - 25 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    userId: 'user_elena_dubai',
    name: 'Elena',
    age: 28,
    gender: 'woman',
    interestedIn: 'men',
    city: 'Dubai',
    country: 'United Arab Emirates',
    showCity: true,
    bio: 'Art curator living between Dubai and Paris. Believer in kindness, deep conversations over dinner, and staying active. Seeking a grounded partner with ambition and a big heart.',
    photos: [
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=800&q=80'
    ],
    interests: ['Contemporary Art', 'Interior Design', 'Equestrian', 'Fine Dining', 'Mindfulness'],
    hobbies: ['Scuba Diving', 'Tennis', 'Gallery Openings', 'Desert Camping'],
    profession: 'Contemporary Art Curator',
    education: 'Sorbonne University',
    languages: ['English', 'French', 'Arabic'],
    relationshipGoal: 'long-term',
    completionPercentage: 100,
    verified: true,
    verificationStatus: 'verified',
    profileVerified: true,
    optedIntoDiscovery: true,
    onlineStatusVisibility: true,
    isIncognito: false,
    lastActiveAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(), // 11 mins ago (Online Now)
    registeredAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    userId: 'user_marcus_toronto',
    name: 'Marcus',
    age: 32,
    gender: 'man',
    interestedIn: 'women',
    city: 'Toronto',
    country: 'Canada',
    showCity: true,
    bio: 'Cardiologist in training. Love staying grounded through trail running, cooking Thai food, and documentary podcasts. Value emotional maturity, warmth, and shared laughter.',
    photos: [
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80'
    ],
    interests: ['Medicine', 'Public Health', 'Trail Running', 'Podcasts', 'Culinary Arts'],
    hobbies: ['Marathon Training', 'Piano', 'Camping in Algonquin', 'Woodworking'],
    profession: 'Resident Physician',
    education: 'University of Toronto',
    languages: ['English'],
    relationshipGoal: 'marriage',
    completionPercentage: 100,
    verified: true,
    verificationStatus: 'verified',
    profileVerified: true,
    optedIntoDiscovery: true,
    onlineStatusVisibility: false,
    isIncognito: false,
    lastActiveAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    registeredAt: new Date(Date.now() - 32 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    userId: 'user_chloe_sydney',
    name: 'Chloe',
    age: 26,
    gender: 'woman',
    interestedIn: 'men',
    city: 'Sydney',
    country: 'Australia',
    showCity: true,
    bio: 'Marine biologist & conservation advocate. Sunrise ocean swims, coastal walks, and flat whites are my non-negotiables. Seeking a kind soul who loves nature and good vibes.',
    photos: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80'
    ],
    interests: ['Ocean Conservation', 'Marine Ecology', 'Surfing', 'Specialty Coffee', 'Yoga'],
    hobbies: ['Freediving', 'Sunset Picnics', 'Pottery', 'Sailing'],
    profession: 'Marine Research Scientist',
    education: 'University of Sydney',
    languages: ['English', 'German'],
    relationshipGoal: 'long-term',
    completionPercentage: 90,
    verified: true,
    verificationStatus: 'verified',
    profileVerified: true,
    optedIntoDiscovery: true,
    onlineStatusVisibility: true,
    isIncognito: false,
    lastActiveAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(), // 8 mins ago (Online Now)
    registeredAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(), // New to HeartMatch!
    updatedAt: new Date().toISOString()
  },
  {
    userId: 'user_julian_berlin',
    name: 'Julian',
    age: 29,
    gender: 'man',
    interestedIn: 'everyone',
    city: 'Berlin',
    country: 'Germany',
    showCity: true,
    bio: 'Creative director & electronic sound designer. Passionate about typography, modular synthesizers, and slow Sunday museum visits. Value self-awareness and open-mindedness.',
    photos: [
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1480429370139-e0132c086e2a?auto=format&fit=crop&w=800&q=80'
    ],
    interests: ['Creative Direction', 'Graphic Design', 'Electronic Music', 'Cinema', 'Modern Philosophy'],
    hobbies: ['Synthesizers', 'Bicycle Touring', 'Film Photography', 'Cooking Ramen'],
    profession: 'Creative Director',
    education: 'Bauhaus University',
    languages: ['English', 'German'],
    relationshipGoal: 'figuring-out',
    completionPercentage: 90,
    verified: true,
    verificationStatus: 'verified',
    profileVerified: true,
    optedIntoDiscovery: true,
    onlineStatusVisibility: true,
    isIncognito: false,
    lastActiveAt: new Date(Date.now() - 13 * 60 * 1000).toISOString(), // 13 mins ago (Online Now)
    registeredAt: new Date(Date.now() - 18 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    userId: 'user_camille_paris',
    name: 'Camille',
    age: 28,
    gender: 'woman',
    interestedIn: 'men',
    city: 'Paris',
    country: 'France',
    showCity: true,
    bio: 'Publishing editor and literary translator. Sucker for vintage bookstores in Le Marais, black coffee, and black-and-white cinema. Looking for warmth, humor, and curiosity.',
    photos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80'
    ],
    interests: ['Literature', 'Translation', 'French Cinema', 'Wine Tasting', 'Architecture'],
    hobbies: ['Creative Writing', 'Ballet', 'Museum Crawls', 'Flea Markets'],
    profession: 'Senior Literary Editor',
    education: 'École Normale Supérieure',
    languages: ['French', 'English', 'Italian'],
    relationshipGoal: 'long-term',
    completionPercentage: 100,
    verified: true,
    verificationStatus: 'verified',
    profileVerified: true,
    optedIntoDiscovery: true,
    onlineStatusVisibility: true,
    isIncognito: false,
    lastActiveAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(), // 6 mins ago (Online Now)
    registeredAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(), // New to HeartMatch!
    updatedAt: new Date().toISOString()
  },
  {
    userId: 'user_mateo_barcelona',
    name: 'Mateo',
    age: 29,
    gender: 'man',
    interestedIn: 'women',
    city: 'Barcelona',
    country: 'Spain',
    showCity: true,
    bio: 'Landscape architect and padel enthusiast. Passionate about Mediterranean botany, seaside sunsets, and Spanish tapas with good friends. Looking for someone grounded and adventurous.',
    photos: [
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80'
    ],
    interests: ['Landscape Design', 'Padel', 'Sailing', 'Spanish Gastronomy', 'Photography'],
    hobbies: ['Hiking Montseny', 'Guitar', 'Cooking Paella', 'Snorkeling'],
    profession: 'Landscape Architect',
    education: 'Universitat Politècnica de Catalunya',
    languages: ['Spanish', 'Catalan', 'English'],
    relationshipGoal: 'marriage',
    completionPercentage: 95,
    verified: true,
    verificationStatus: 'verified',
    profileVerified: true,
    optedIntoDiscovery: true,
    onlineStatusVisibility: false,
    isIncognito: false,
    lastActiveAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    registeredAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(), // New to HeartMatch!
    updatedAt: new Date().toISOString()
  },
  {
    userId: 'user_chiara_milan',
    name: 'Chiara',
    age: 27,
    gender: 'woman',
    interestedIn: 'men',
    city: 'Milan',
    country: 'Italy',
    showCity: true,
    bio: 'Fashion product designer with an obsession for Italian espresso, mid-century furniture, and weekend trips to Lake Como. Looking for deep conversations and authentic laughs.',
    photos: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80'
    ],
    interests: ['Fashion Design', 'Mid-Century Modern', 'Specialty Coffee', 'Contemporary Art', 'Travel'],
    hobbies: ['Pilates', 'Vespa Touring', 'Cooking Risotto', 'Film Photography'],
    profession: 'Apparel Product Designer',
    education: 'Politecnico di Milano',
    languages: ['Italian', 'English'],
    relationshipGoal: 'long-term',
    completionPercentage: 100,
    verified: true,
    verificationStatus: 'verified',
    profileVerified: true,
    optedIntoDiscovery: true,
    onlineStatusVisibility: true,
    isIncognito: false,
    lastActiveAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(), // 7 mins ago (Online Now)
    registeredAt: new Date(Date.now() - 21 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    userId: 'user_lucas_amsterdam',
    name: 'Lucas',
    age: 31,
    gender: 'man',
    interestedIn: 'women',
    city: 'Amsterdam',
    country: 'Netherlands',
    showCity: true,
    bio: 'Renewable energy engineer, cyclist, and vinyl collector. Love exploring canal cafes, reading sci-fi, and making weekend brunches. Seeking a real, grounded connection.',
    photos: [
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80'
    ],
    interests: ['Clean Energy', 'Cycling', 'Vinyl Records', 'Specialty Coffee', 'Architecture'],
    hobbies: ['Road Biking', 'Brewing Kombucha', 'Board Games', 'Woodworking'],
    profession: 'Clean Tech Systems Engineer',
    education: 'Delft University of Technology',
    languages: ['Dutch', 'English', 'German'],
    relationshipGoal: 'marriage',
    completionPercentage: 95,
    verified: true,
    verificationStatus: 'verified',
    profileVerified: true,
    optedIntoDiscovery: true,
    onlineStatusVisibility: true,
    isIncognito: false,
    lastActiveAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(), // 10 mins ago (Online Now)
    registeredAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(), // New to HeartMatch!
    updatedAt: new Date().toISOString()
  }
];

export const INITIAL_PROFILE_ACTIVITIES: Record<string, {
  userId: string;
  viewsCount: number;
  likesReceivedCount: number;
  matchesCount: number;
  lastActiveAt: string;
  isOnline: boolean;
}> = {
  user_sophia_ny: {
    userId: 'user_sophia_ny',
    viewsCount: 342,
    likesReceivedCount: 184,
    matchesCount: 26,
    lastActiveAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    isOnline: true,
  },
  user_liam_london: {
    userId: 'user_liam_london',
    viewsCount: 289,
    likesReceivedCount: 147,
    matchesCount: 19,
    lastActiveAt: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
    isOnline: true,
  },
  user_elena_dubai: {
    userId: 'user_elena_dubai',
    viewsCount: 412,
    likesReceivedCount: 231,
    matchesCount: 34,
    lastActiveAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
    isOnline: true,
  },
  user_marcus_toronto: {
    userId: 'user_marcus_toronto',
    viewsCount: 215,
    likesReceivedCount: 98,
    matchesCount: 14,
    lastActiveAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    isOnline: false,
  },
  user_chloe_sydney: {
    userId: 'user_chloe_sydney',
    viewsCount: 198,
    likesReceivedCount: 112,
    matchesCount: 15,
    lastActiveAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    isOnline: true,
  },
  user_julian_berlin: {
    userId: 'user_julian_berlin',
    viewsCount: 267,
    likesReceivedCount: 135,
    matchesCount: 18,
    lastActiveAt: new Date(Date.now() - 13 * 60 * 1000).toISOString(),
    isOnline: true,
  },
  user_camille_paris: {
    userId: 'user_camille_paris',
    viewsCount: 380,
    likesReceivedCount: 195,
    matchesCount: 28,
    lastActiveAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    isOnline: true,
  },
  user_mateo_barcelona: {
    userId: 'user_mateo_barcelona',
    viewsCount: 189,
    likesReceivedCount: 88,
    matchesCount: 12,
    lastActiveAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    isOnline: false,
  },
  user_chiara_milan: {
    userId: 'user_chiara_milan',
    viewsCount: 356,
    likesReceivedCount: 178,
    matchesCount: 24,
    lastActiveAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    isOnline: true,
  },
  user_lucas_amsterdam: {
    userId: 'user_lucas_amsterdam',
    viewsCount: 228,
    likesReceivedCount: 104,
    matchesCount: 16,
    lastActiveAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    isOnline: true,
  },
};
